### ISSUE TITLE
Crash on start ViaStitching plugin

### ISSUE THREAD

**Issue by Flamy69** [jsreynaud/kicad-action-scripts#28] opened 2020-10-14 13:02 UTC
I am on version of KiCad 
![image](https://user-images.githubusercontent.com/38912805/95992126-e4361980-0e2d-11eb-9987-03369aa6af89.png)
and when I hit icon of viastitching, i get this error message:
![image](https://user-images.githubusercontent.com/38912805/95992191-fa43da00-0e2d-11eb-932b-bb4cbd39a009.png)

Am I doing womething wrong or ? I am new at KiCad and at GitHub as well, so please be nice, if it is stupid question :D

Thank you very much in advance.
Marek

**Comment by zenz** [comment] 2020-12-22 13:41
This plugin only supports KICAD 5.1.x

**Comment by jsreynaud** [comment] 2021-01-28 15:16
Duplicate of #27

**Closed as completed by jsreynaud** 2021-01-28 15:16 UTC
